//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmeWebApps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AME_BUILD_SHEET
    {
        public int BUILD_SHEET_ID { get; set; }
        public string PRINT_DATE { get; set; }
        public string INSTALL_DATE { get; set; }
        public string SHIP_BY_DATE { get; set; }
        public Nullable<int> PROFILE_SIZE { get; set; }
        public int CLIENT_ID { get; set; }
        public Nullable<int> NUM_ZONES { get; set; }
        public string COMPANY_NAME { get; set; }
        public int SYSTEM_ID { get; set; }
        public string BRANCH_NAME { get; set; }
        public string USE_REFURB { get; set; }
        public string REPLACING_TYPE { get; set; }
        public string COMM_TYPE { get; set; }
        public string ARRIVE_BY_DATE { get; set; }
        public string PACKAGING_TYPE { get; set; }
        public string RETURN_LABEL { get; set; }
        public string SHIP_TO_TYPE { get; set; }
        public string CUSTOM_ADDR_ATTN { get; set; }
        public string CUSTOM_ADDR_1 { get; set; }
        public string CUSTOM_ADDR_2 { get; set; }
        public string CUSTOM_ADDR_CITY { get; set; }
        public string CUSTOM_ADDR_STATE { get; set; }
        public string CUSTOM_ADDR_ZIP { get; set; }
        public string ADDITIONAL_INSTRUCTIONS { get; set; }
        public string DATE_BUILT { get; set; }
        public string NEW_OR_REFURB { get; set; }
        public string DATE_SHIPPED { get; set; }
        public string TAG_NUMBER { get; set; }
        public string TRACKING_NUM { get; set; }
        public string RETURN_SLIP_TRACKING_NUM { get; set; }
        public string SHIPPING_METHOD { get; set; }
        public string PRINTED_BY { get; set; }
        public string REPLACING_NAME { get; set; }
        public Nullable<int> REPLACING_SYSTEM_ID { get; set; }
        public Nullable<System.DateTime> INSERT_DATE { get; set; }
        public Nullable<System.DateTime> EDITED_DATE { get; set; }
    }
}
