//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmeWebApps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AME_CATEGORY_TREE
    {
        public string CATEGORY_ID { get; set; }
        public string PARENT_CATEGORY_ID { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<System.DateTime> DATE_MODIFIED { get; set; }
        public IList<AME_CATEGORY_TREE> Children { get; set; }
        public AME_CATEGORY_TREE()
        {
            Children = new List<AME_CATEGORY_TREE>();
        }
    }
}
