//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmeWebApps.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NewCatModels : DbContext
    {
        public NewCatModels()
            : base("name=NewCatModels")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AME_CATEGORY_TREE> AME_CATEGORY_TREE { get; set; }
        public DbSet<RPM_CATEGORY> RPM_CATEGORY { get; set; }
        public DbSet<RPM_MUSIC> RPM_MUSIC { get; set; }
        public DbSet<RPM_MUSIC_CATEGORY> RPM_MUSIC_CATEGORY { get; set; }
    }
}
