//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmeWebApps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RPM_MUSIC
    {
        public int MUSIC_ID { get; set; }
        public string TITLE { get; set; }
        public string EDIT { get; set; }
        public string DISPLAY_ARTIST { get; set; }
        public Nullable<short> YEAR_PUBLISHED { get; set; }
        public Nullable<short> RPM_RATING { get; set; }
        public Nullable<short> INTRO { get; set; }
        public Nullable<short> RUN { get; set; }
        public Nullable<short> EOM_TIME { get; set; }
        public string END_TYPE { get; set; }
        public Nullable<short> FADE { get; set; }
        public string BPM { get; set; }
        public string RPM_CATEGORY_ID { get; set; }
        public string IS_INTERNET_OK { get; set; }
        public string RE_DISTRIBUTE_TO_AME { get; set; }
        public string AME_DISTRIBUTION_STATE { get; set; }
        public string AME_DISTRIBUTION_COMMENTS { get; set; }
        public string VERIFICATION_STATE { get; set; }
        public string VERIFICATION_COMMENTS { get; set; }
        public string VERIFIED_BY { get; set; }
        public Nullable<System.DateTime> DATE_ENTERED { get; set; }
        public Nullable<System.DateTime> DATE_MODIFIED { get; set; }
        public string STREAMING_SAMPLE_FILE { get; set; }
        public string AUDIO_TYPE { get; set; }
    }
}
