//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmeWebApps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RPM_MUSIC_CATEGORY
    {
        public int MUSIC_ID { get; set; }
        public string CATEGORY_ID { get; set; }
        public string SERVICE_TYPE { get; set; }
        public Nullable<System.DateTime> DATE_MODIFIED { get; set; }
        public Nullable<int> TEMPO { get; set; }
        public Nullable<int> INTENSITY { get; set; }
    }
}
