//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmeWebApps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RPM_CLIENT_SYSTEM
    {
        public int SYSTEM_ID { get; set; }
        public int CLIENT_ID { get; set; }
        public int LOCATION_ID { get; set; }
        public int PROFILE_ID { get; set; }
        public string SYSTEM_STATUS { get; set; }
        public string COMPUTER_NAME { get; set; }
        public Nullable<System.DateTime> DATE_REQUIRED { get; set; }
        public Nullable<System.DateTime> DATE_PROMISED { get; set; }
        public Nullable<System.DateTime> DATE_BUILT { get; set; }
        public Nullable<System.DateTime> DATE_SHIPPED { get; set; }
        public string SYSTEM_TYPE { get; set; }
        public Nullable<System.DateTime> DATE_INSTALLED { get; set; }
        public Nullable<System.DateTime> DATE_LAST_COMM { get; set; }
        public Nullable<System.DateTime> DATE_NEXT_COMM { get; set; }
        public Nullable<System.DateTime> DATE_ALERT_COMM { get; set; }
        public string COMM_METHOD { get; set; }
        public string DIAL_PREFIX { get; set; }
        public string USE_DHCP_FOR_IP { get; set; }
        public string IP_ADDRESS { get; set; }
        public string IP_SUBNET_MASK { get; set; }
        public string IP_GATEWAY { get; set; }
        public string USE_DHCP_FOR_DNS { get; set; }
        public string IP_DNS_SERVERS { get; set; }
        public Nullable<int> COMM_FREQ_VALUE { get; set; }
        public string COMM_FREQ_UNITS { get; set; }
        public Nullable<int> COMM_WINDOW_START { get; set; }
        public Nullable<int> COMM_WINDOW_STOP { get; set; }
        public Nullable<int> COMM_RETRY_LIMIT { get; set; }
        public Nullable<int> COMM_RETRY_VALUE { get; set; }
        public string COMM_RETRY_UNITS { get; set; }
        public string LAST_COMM_UPDATE { get; set; }
        public Nullable<System.DateTime> COMM_UPDATE_CREATED { get; set; }
        public string COMM_DELIVERY_METHOD { get; set; }
        public Nullable<System.DateTime> EXPIRATION_DATE { get; set; }
        public string FORCE_DEACTIVATION { get; set; }
        public Nullable<System.DateTime> UPDATES_FEEDBACK_DATE { get; set; }
        public Nullable<System.DateTime> PLAYED_FEEDBACK_DATE { get; set; }
        public Nullable<System.DateTime> EVENTS_FEEDBACK_DATE { get; set; }
        public Nullable<System.DateTime> LAST_DIAG_DATE { get; set; }
        public Nullable<System.DateTime> SYSTEM_EXPIRES { get; set; }
        public string PROXY_SERVER { get; set; }
        public Nullable<int> PROXY_PORT { get; set; }
        public string PROXY_USER { get; set; }
        public string PROXY_PASSWORD { get; set; }
        public Nullable<int> NEW_WINDOW_START { get; set; }
        public Nullable<int> NEW_WINDOW_STOP { get; set; }
        public Nullable<int> ACTIVE_CATALOG_VER_NUM { get; set; }
        public Nullable<int> ACTIVE_PROFILE_VER_NUM { get; set; }
        public Nullable<int> ORIGINAL_PROFILE_ID { get; set; }
        public string PASSWORD { get; set; }
        public bool ENABLED { get; set; }
        public System.DateTime DATE_LAST_UPLOAD { get; set; }
        public string IP_ADDRESS_SERVER { get; set; }
        public string OBEY_COMM_WINDOW { get; set; }
        public string LAST_COMM_METHOD { get; set; }
        public Nullable<int> BPS { get; set; }
        public string AUDIO_CARD_TYPE { get; set; }
        public Nullable<int> VIDEO_CAPS { get; set; }
    }
}
