//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmeWebApps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RPM_CLIENT_ADDRESS
    {
        public int ADDRESS_ID { get; set; }
        public string COMPANY_NAME { get; set; }
        public string BRANCH { get; set; }
        public string ATTENTION { get; set; }
        public string ADDRESS_1 { get; set; }
        public string ADDRESS_2 { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string COUNTRY { get; set; }
        public string ZIP { get; set; }
        public Nullable<int> COMPANY_ID { get; set; }
        public string COMPANY_TYPE { get; set; }
        public string NOTES { get; set; }
        public Nullable<int> ORIG_ADDRESS_ID { get; set; }
    }
}
