//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmeWebApps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RPM_CLIENT_LOCATION
    {
        public int LOCATION_ID { get; set; }
        public int CLIENT_ID { get; set; }
        public int ADDRESS_ID { get; set; }
        public string BILL_TO_POLICY { get; set; }
        public Nullable<int> BILL_TO_ADDRESS_ID { get; set; }
        public string SHIP_TO_POLICY { get; set; }
        public Nullable<int> SHIP_TO_ADDRESS_ID { get; set; }
        public Nullable<decimal> MONTHLY_SERVICE_FEE { get; set; }
        public Nullable<int> MONTHS_PER_BILL_PERIOD { get; set; }
        public Nullable<int> BILL_AHEAD_DAYS { get; set; }
        public Nullable<System.DateTime> SERVICE_START_DATE { get; set; }
        public string SEASON_START { get; set; }
        public string SEASON_END { get; set; }
        public Nullable<int> SEASON_START_MMDD { get; set; }
        public Nullable<int> SEASON_END_MMDD { get; set; }
        public Nullable<int> SYSTEM_GRACE_PERIOD { get; set; }
        public Nullable<int> ZONE_ID { get; set; }
        public Nullable<System.DateTime> PREV_BILL_THROUGH_DATE { get; set; }
        public string HAS_PHYSICAL_ACTIVITY { get; set; }
        public string RUNS_PAID_ADVERTISING { get; set; }
        public string PAYS_OWN_BMI { get; set; }
        public string PAYS_OWN_ASCAP { get; set; }
        public string PAYS_OWN_SESAC { get; set; }
        public string CHARGES_ADMISSION { get; set; }
        public Nullable<int> FLOOR_COUNT { get; set; }
        public string PAYS_OWN_AFM { get; set; }
        public string NOTES { get; set; }
        public string UPDATE_METHOD { get; set; }
        public Nullable<int> DISC_THRESHOLD { get; set; }
        public string UPDATE_METHOD_REASON { get; set; }
        public string LOCATION_TYPE { get; set; }
        public Nullable<System.DateTime> QC_CALL_DATE { get; set; }
        public string LOCATION_STATUS { get; set; }
        public Nullable<int> ORIG_LOCATION_ID { get; set; }
        public string ASCAP_RATE_PLAN { get; set; }
    }
}
