//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmeWebApps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RPM_CATEGORY
    {
        public string SERVICE_TYPE { get; set; }
        public string CATEGORY_ID { get; set; }
        public string DESCRIPTION { get; set; }
        public string IS_CLIENT { get; set; }
        public string IS_MUSIC { get; set; }
        public Nullable<System.DateTime> DATE_MODIFIED { get; set; }
        public string IS_LIBRARY { get; set; }
        public string IS_RESOURCE_ONLY { get; set; }
        public string IS_SEASONAL { get; set; }
        public string COMMENTS { get; set; }
        public string DEPLOY_REPROCESSED { get; set; }
        public string IS_NEW_MODEL { get; set; }
        public string IS_RESTRICTED_TO_AME { get; set; }
        public string CATEGORY_TYPE { get; set; }
    }
}
